services:
  mysql:
    image: mysql:8.0
    container_name: encurtador-url-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: encurtador_url_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - encurtador_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: encurtador-url-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/encurtador_url_db
      SHADOW_DATABASE_URL: mysql://root:root@mysql:3306/encurtador_url_db_shadow
    networks:
      - encurtador_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  encurtador_network:
    driver: bridge